from enum import Enum

class OpportunityState(Enum):
    DISCOVERED = "DISCOVERED"
    ANALYZING = "ANALYZING"
    COUNCIL_REVIEW = "COUNCIL_REVIEW"
    SIMULATION_PENDING = "SIMULATION_PENDING"
    SIMULATING = "SIMULATING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    VENTURE_CREATED = "VENTURE_CREATED"
    FAILED = "FAILED"
    LEARNED = "LEARNED"
