import sys
import os
import asyncio
from typing import Dict, Any

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from raphael_core.kernel.registry import registry
from raphael_core.kernel.providers.workflow.python_provider import PythonProvider
from raphael_core.kernel.providers.workflow.executor_provider import ExecutorProvider
from raphael_core.kernel.models.workflow import WorkflowExecution, WorkflowStep, WorkflowStatus
from raphael_core.kernel.repositories.idempotency_store import IdempotencyStore

async def main():
    print("==========================================")
    print("   STARTING MISSION 3 LIVE ORCHESTRATION  ")
    print("==========================================\n")
    
    # 1. Setup Environment
    # We clear the idempotency db to ensure a clean test
    if os.path.exists(".system_generated/idempotency.db"):
        os.remove(".system_generated/idempotency.db")
        
    # 2. Setup Providers
    provider = PythonProvider()
    executor = ExecutorProvider(provider)
    
    execution = WorkflowExecution(workflow_id="mission_3_live_123")
    
    # We define a multi-stage workflow. 
    # Stage 3 is the critical publish step.
    steps = [
        WorkflowStep(id="step_1", name="Research Market", action="echo", parameters={"message": "Market research complete"}),
        WorkflowStep(id="step_2", name="Generate Asset", action="echo", parameters={"message": "Asset generated"}),
        WorkflowStep(id="step_3", name="Publish Listing", action="commerce.publish", parameters={
            "title": "Summer Vibes POD Shirt",
            "description": "Premium summer shirt for 2024.",
            "shop_id": "123",
            "hard_kill": True # <--- RACE CONDITION INJECTION
        }),
        WorkflowStep(id="step_4", name="Notify", action="echo", parameters={"message": "Notified team of success!"})
    ]
    
    print("[PHASE 1] Initial run with injected race condition crash (Hard Kill)...")
    
    try:
        for step in steps:
            print(f"[ORCHESTRATOR] Executing Stage: {step.action}")
            await executor.execute_step(step, execution)
            print(f"[ORCHESTRATOR] [OK] Stage {step.action} PASSED")
    except SystemExit as e:
        print(f"\n[DAEMON KILLED] {e}")
        
    print("\n[SYSTEM] Daemon rebooted. Recovering execution state...")
    print("[PHASE 2] Resuming execution...")
    
    # Clear the hard_kill flag so the retry can actually complete
    steps[2].parameters["hard_kill"] = False
    
    # Fetch from our mock DB state: loop over steps that didn't complete
    for step in steps:
        if execution.step_executions.get(step.id) != WorkflowStatus.COMPLETED:
            print(f"[ORCHESTRATOR] Resuming Stage: {step.action} (Step {step.id})")
            await executor.execute_step(step, execution)
            print(f"[ORCHESTRATOR] [OK] Stage {step.action} PASSED")
            
    print("\n[SUCCESS] Mission 3 completed gracefully!")
    
    # Let's verify the mock server to see exactly how many listings were created.
    import urllib.request
    import json
    
    # Our idempotency key for this run will be the idempotency_key generated by ExecutorProvider.
    # We can fetch all listings to count them.
    req = urllib.request.Request("http://localhost:8082/v3/application/shops/123/listings")
    try:
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode())
            print(f"\n[VERIFICATION] Listings found on Etsy mock: {data['count']}")
            for l in data['results']:
                print(f"  -> ID: {l['id']} | SKU: {l['sku']} | Title: {l['title']}")
    except Exception as e:
        print(f"Failed to verify mock server: {e}")


if __name__ == "__main__":
    asyncio.run(main())
