from __future__ import annotations

import re
import unittest
from pathlib import Path


class DashboardRouteTests(unittest.TestCase):
    def test_required_routes_and_command_bus_only_chat_are_present(self) -> None:
        text = Path("C:/RaphaelOS/dashboard/app.py").read_text(encoding="utf-8")
        routes = set(re.findall(r'@app\.(?:get|post)\("([^"]+)"', text))
        self.assertTrue({"/", "/api/overview", "/api/health", "/api/chat"}.issubset(routes))
        self.assertIn('bus.route(phrase, "dashboard", COMMAND_BUS_SESSION)', text)
        self.assertIn("No fallback route was used", text)
        self.assertNotIn("using legacy dashboard routing", text)

    def test_matrix_and_builder_renderers_remain_registered(self) -> None:
        text = Path("C:/RaphaelOS/dashboard/app.py").read_text(encoding="utf-8")
        self.assertIn("builder:renderBuilder", text)
        self.assertIn("daily:renderDailyOperatingLoop", text)
        self.assertIn('["daily", "Daily Operating Loop"]', text)
        self.assertIn("POD Pipeline Quick Actions", text)
        self.assertIn("ComfyUI Output Bridge", text)
        self.assertIn("Copy generation debug command", text)
        self.assertIn("Generation debug files", text)
        self.assertIn("pod-generation-debug", text)
        self.assertIn("request.image_count > 0", text)
        self.assertIn("Typography & Composition Engine", text)
        self.assertIn("pod_typography_create", text)
        self.assertIn("pod_print_export", text)
        self.assertIn("Bootstrap / Launcher", text)
        self.assertIn("bootstrap-health-pill", text)
        self.assertIn("restart Raphael services", text)
        self.assertIn("Service Manager", text)
        self.assertIn('"/api/services"', text)
        self.assertIn('"/api/services/status"', text)
        self.assertIn('"/api/services/start"', text)
        self.assertIn('"/api/services/stop"', text)
        self.assertIn('"/api/services/restart"', text)
        self.assertIn('"/api/services/health"', text)
        self.assertIn('"/api/services/start-stack"', text)
        self.assertIn("Start Creative Stack", text)
        self.assertIn("Restart Failed Services", text)
        self.assertIn("Start Qdrant", text)
        self.assertIn("Restart Qdrant", text)
        self.assertIn("Open Qdrant URL", text)
        self.assertIn("Docker Health", text)
        self.assertIn("Show Docker Logs", text)
        self.assertIn("Permissioned Internet Access", text)
        self.assertIn("AI Overview", text)
        self.assertIn("Show Sources", text)
        self.assertIn("Show Snippets", text)
        self.assertIn("Show Raw JSON", text)
        self.assertIn("Save to Knowledge", text)
        self.assertIn("Pending Search Requests", text)
        self.assertIn("Saved Sources", text)
        self.assertIn("Internet Safety Policy", text)
        self.assertIn("Headless Search Results", text)
        self.assertIn("Niche Scoring", text)
        self.assertIn("Start Research Stack", text)
        self.assertIn('["workflowrunner", "Workflow Runner"]', text)
        self.assertIn("workflowrunner:renderWorkflowRunner", text)
        self.assertIn('"/api/workflow-runner/execute"', text)
        self.assertIn('"/api/workflow-runner/cancel"', text)
        self.assertIn('"/api/workflow-runner/monitor"', text)
        self.assertIn('"/api/workflow-runner/result"', text)
        self.assertIn("Execution Logs", text)
        self.assertIn("Failures and Recovery", text)
        self.assertIn("Archive Details", text)
        self.assertIn("workflow_archive_show", text)
        self.assertIn("workflow-archive-show", text)
        self.assertIn("workflow-archive-search", text)
        self.assertIn("workflow-archive-summary", text)
        self.assertIn("Potential Raphael Uses", text)
        self.assertIn('["selfhealing", "Self-Healing"]', text)
        self.assertIn("selfhealing:renderSelfHealing", text)
        self.assertIn('"/api/self-healing"', text)
        self.assertIn('"/api/self-healing/{action}"', text)
        self.assertIn("Self-Healing Summary", text)
        self.assertIn("Create repair plan", text)
        self.assertIn("Approval required", text)
        self.assertIn("window.__classicRenderMap", text)
