from enum import Enum

class OperatorState(str, Enum):
    IDLE = "IDLE"
    MONITORING = "MONITORING"
    ANALYZING_HEALTH = "ANALYZING_HEALTH"
    IDENTIFYING_OPPORTUNITIES = "IDENTIFYING_OPPORTUNITIES"
    STRATEGIZING = "STRATEGIZING"
    REQUESTING_RESOURCES = "REQUESTING_RESOURCES"
    AUTHORITY_CHECK = "AUTHORITY_CHECK"
    COUNCIL_REVIEW = "COUNCIL_REVIEW"
    EXECUTING = "EXECUTING"
    MEASURING = "MEASURING"
    LEARNING = "LEARNING"
    OPTIMIZING = "OPTIMIZING"
    BLOCKED = "BLOCKED"
    ESCALATING = "ESCALATING"
    PAUSED = "PAUSED"
