from typing import List, Dict, Any, Optional
import uuid

class MissionProposal:
    """
    MissionProposal represents a structured execution plan generated by the Executive Chat Router.
    It serves as the contract between the Operator interface and the execution layer (Command Bus).
    """
    def __init__(
        self,
        intent: str,
        objective: str,
        workflow_id: Optional[str] = None,
        workflow_name: Optional[str] = None,
        agents: List[str] = None,
        tools: List[str] = None,
        capabilities_used: List[str] = None,
        simulation: Dict[str, Any] = None,
        risk_level: str = "Unknown",
        confidence_score: float = 0.0,
        reasoning_summary: str = "",
        requires_approval: bool = True,
        status: str = "Awaiting Approval"
    ):
        self.id = f"proposal_{uuid.uuid4().hex[:8]}"
        self.intent = intent
        self.objective = objective
        self.workflow_id = workflow_id
        self.workflow_name = workflow_name
        self.agents = agents or []
        self.tools = tools or []
        self.capabilities_used = capabilities_used or []
        self.simulation = simulation or {"cost": "$0", "runtime": "Unknown"}
        self.risk_level = risk_level
        self.confidence_score = confidence_score
        self.reasoning_summary = reasoning_summary
        self.requires_approval = requires_approval
        self.status = status

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "intent": self.intent,
            "objective": self.objective,
            "workflow_id": self.workflow_id,
            "workflow_name": self.workflow_name,
            "agents": self.agents,
            "tools": self.tools,
            "capabilities_used": self.capabilities_used,
            "simulation": self.simulation,
            "risk_level": self.risk_level,
            "confidence_score": self.confidence_score,
            "reasoning_summary": self.reasoning_summary,
            "requires_approval": self.requires_approval,
            "status": self.status
        }
